name: Continuous integration
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get -y install clang-tidy
    - uses: actions/checkout@v2
    - name: Test
      run: |
        cmake .
        make
        make test
